### ISSUE TITLE
Add Rule Discord

### ISSUE THREAD

**Issue by sentaro-yellow** [malikshi/open_clash#10]
![image](https://user-images.githubusercontent.com/58460299/209548594-44f452bb-0925-4710-b284-741fce9f6932.png)
Server discord masuk ke direct

**Comment by rfxcll** [comment]
Voice chat Discord?

**Comment by sentaro-yellow** [comment]
> 

yep, asumiku karna engga ada domain nya di server discord. Tp bingung kenapa engga masuk rule umum aja dari pada direct.
Sebenernya bisa di fix kalo rule direct nya di gantiin proxy

**Comment by rfxcll** [comment]
Harusnya ini masuk ke PortGames malah.
Kan UDP dan bukan Port Umum, tapi kok malah ke direct. Saya bingung disitu.

Soalnya rule direct di repo gk ada port itu.
Ato rule directnya udah beda ato di edit sendiri?

**Comment by sentaro-yellow** [comment]
> Harusnya ini masuk ke PortGames malah. Kan UDP dan bukan Port Umum, tapi kok malah ke direct. Saya bingung disitu.
> 
> Soalnya rule direct di repo gk ada port itu. Ato rule directnya udah beda ato di edit sendiri?

Jadi di situasi saya:
- Run confignya di mode rule (tun) fake-ip
- Kalo abang tanya di direct ada port nya, memang ada
Ini port yang ada di direct
  - DST-PORT,3478
  - DST-PORT,4244
  - DST-PORT,5222
  - DST-PORT,5223
  - DST-PORT,5228
  - DST-PORT,5288
  - DST-PORT,5242
  - DST-PORT,5349
  - DST-PORT,34784
  - DST-PORT,45395
  - DST-PORT,50318
  - DST-PORT,59234
  - DST-PORT,12222
  - DST-PORT,11112
  - DST-PORT,25566

**Comment by mizuhashikuniumi** [comment]
@sentaro-yellow Ok

**Comment by rfxcll** [comment]
> > Harusnya ini masuk ke PortGames malah. Kan UDP dan bukan Port Umum, tapi kok malah ke direct. Saya bingung disitu.
> > 
> > Soalnya rule direct di repo gk ada port itu. Ato rule directnya udah beda ato di edit sendiri?
> 
> Jadi di situasi saya:
> - Run confignya di mode rule (tun) fake-ip
> - Kalo abang tanya di direct ada port nya, memang ada
> Ini port yang ada di direct
>   - DST-PORT,3478
>   - DST-PORT,4244
>   - DST-PORT,5222
>   - DST-PORT,5223
>   - DST-PORT,5228
>   - DST-PORT,5288
>   - DST-PORT,5242
>   - DST-PORT,5349
>   - DST-PORT,34784
>   - DST-PORT,45395
>   - DST-PORT,50318
>   - DST-PORT,59234
>   - DST-PORT,12222
>   - DST-PORT,11112
>   - DST-PORT,25566
>  

Kan gk ada port 50005.
Itu yg saya maksudkan.

**Comment by rfxcll** [comment]
> What Port Does Discord Use?
> Discord uses port 443 TCP for text chat and a random port between 50,000 and 65,535 UDP for voice chat. This means you’ll need to open port 443 for text chat and all ports between 50,000 and 65,535 if you want Discord to work properly with voice and text chat.
> Source : https://streamersplaybook.com/what-port-does-discord-use/

Jadi yah, nope sih kalo dari ane.

**Comment by sentaro-yellow** [comment]
yaudah close aja bang gpp.
