### ISSUE TITLE
Latest ver guide needed

### ISSUE THREAD

**Issue by adisubagja** [malikshi/open_clash#14]
Update om ui interface openclash udah update 😂 walau kurleb sama penamaan nya lokasinya kan yang baru dateng suka bingung
semoga di anu

**Comment by malikshi** [comment]
> Update om ui interface openclash udah update 😂 walau kurleb sama penamaan nya lokasinya kan yang baru dateng suka bingung semoga di anu

Send me stb bruh 🥺

**Comment by malikshi** [comment]
ada OC di armbian kah?
