### ISSUE TITLE
Rule games

### ISSUE THREAD

**Issue by NICE28004** [malikshi/open_clash#7]
Add rule plis. 

Boom beach FL

**Comment by malikshi** [comment]
Can you share the link of games?

**Comment by NICE28004** [comment]
https://play.google.com/store/apps/details?id=com.spaceapegames.boombeach.frontlines

Kalo bisa sama ini bang game viral marvel snap

https://play.google.com/store/apps/details?id=com.nvsgames.snap

**Comment by malikshi** [comment]
Coba capture pakai ini.
Check out "PCAPdroid - network monitor"
https://play.google.com/store/apps/details?id=com.emanuelef.remote_capture

**Comment by NICE28004** [comment]
Apl: Boom Beach FL (10184)
Protokol: TLS (TCP)
SNI: gateway.prod.otter.apelabs.net
Sumber: 10.215.173.1:33388
Tujuan: 35.86.6.228:443
Status: Tertutup
Lalu lintas: 128 B diterima — 329 B terkirim
Paket: 3 diterima — 3 terkirim
Muatan: 189 B
Durasi: > 1 m
Terlihat: 10/30/22 08:28:53.040
Terakhir terlihat: 10/30/22 08:29:56.903

**Comment by malikshi** [comment]
capture again!
